package tutor

import (
	"database/sql"
	"fmt"
	"log"
	"sort"
	"time"
	"tutree/student-apis/config"
	"tutree/student-apis/utility"

	"github.com/lib/pq"
)

type Tutor struct {
	ID                    int    `json:"id,omitempty"`
	TutorEmail            string `json:"email_id,omitempty"`
	Phone                 string `json:"phone_number,omitempty"`
	TutorName             string `json:"tutor_name,omitempty"`
	PictureURL            string `json:"picture_url,omitempty"`
	CreatedAt             string `json:"created_at,omitempty"`
	HashPassword          string `json:"encrypted_password,omitempty"`
	QueryParams           string `json:"query_params,omitempty"`
	TeachesTo             string `json:"teaches_to,omitempty"`
	Timezone              string `json:"timezone,omitempty"`
	ZoomLink              string `json:"meeting_link,omitempty"`
	AutogeneratedPassword bool   `json:"autogenerated_password,omitempty"`
}

type AvailableSlot struct {
	Date  string `json:"date,omitempty"`
	Day   string `json:"day,omitempty"`
	Slots []Slot `json:"slots,omitempty"`
}

type Slot struct {
	TutorID int         `json:"tutor_id,omitempty"`
	Start   string      `json:"start"`
	End     string      `json:"end"`
	Dates   []SlotDates `json:"dates,omitempty"`
}
type SlotDates struct {
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

// GetAvailableTutor retrieves an available tutor for a given session start time.
// It queries the database to find tutors who are not booked for a session at the specified time
// and randomly selects one available tutor from the list.
//
// Input Parameters:
// - sessionStart: time.Time - The start time of the session for which to find an available tutor.
//
// Output:
// - (int, error) - The function returns the ID of a randomly selected available tutor and an error if any issues occur.
//   - int: The ID of the available tutor. If no tutor is available, returns 0.
//   - error: An error object if there are issues connecting to the database, querying, or scanning results; otherwise, nil.
//
// On success, the function will return the ID of a randomly selected tutor from the available tutors.
//
// On failure, it logs the error and returns a 0 and an error message.
// func GetAvailableTutor(userID int, startSession time.Time) (int, error) {
// 	// Get a connection to the database.
// 	db, err := config.GetDB2()
// 	// If there is an error connecting to the database, log the error and return 0 and the error.
// 	if err != nil {
// 		log.Println("GetAvailableTutor: failed while trying to connect with database with error: ", err)
// 		return 0, err
// 	}
// 	defer db.Close()
// 	// Ensure the database connection is closed when the function returns.

// 	// Define the SQL query to select tutor IDs who are not booked for a session at the specified start time
// 	// and whose session status is neither 'active' nor 'started'.
// 	query :=
// 		`SELECT
// 				t.id
// 		FROM
// 				tutor t
// 		WHERE
// 				t.id NOT IN
// 		(SELECT
// 			s.tutor_id
//    		 FROM
// 		 	session s
//     	WHERE
// 			s.user_id = $1 AND
// 			s.session_start = $2 AND
//       	 	s.status IN ('active', 'started'))`
// 	// Execute the query, passing in the session start time as a parameter.

// 	var tutorId []int
// 	rows, err := db.Query(query, userID, startSession)
// 	// If there is an error executing the query, log the error and return 0 and the error.
// 	if err != nil {
// 		log.Println("GetAvailableTutor: failed while trying to connect with database with error: ", err)
// 		return 0, err
// 	}
// 	defer rows.Close()
// 	// Ensure the result set is closed when the function returns.

// 	// Iterate over the rows in the result set to collect available tutor IDs.
// 	for rows.Next() {
// 		var id int
// 		err := rows.Scan(&id)
// 		// If there is an error scanning the tutor ID from the result set, log the error and return 0 and the error.
// 		if err != nil {
// 			log.Println("GetAvailableTutor: failed while trying to scan tutor id from row with error: ", err)
// 			return 0, err
// 		}
// 		tutorId = append(tutorId, id)
// 		// Append the tutor ID to the list of available tutors.
// 	}
// 	// Check if there are any available tutors.
// 	if len(tutorId) == 0 {
// 		// If no tutors are available for the given time slot, log the message and return 0 with a descriptive error.
// 		log.Println("GetAvailableTutor: failed, no tutor available at given time slot.")
// 		return 0, errors.New("no tutor available at given time slot")
// 	}
// 	// Randomly select a tutor from the list of available tutors.
// 	randomIndex := rand.Intn(len(tutorId))
// 	return tutorId[randomIndex], nil
// }

func GetAvailableDemoSlots(startDate, endDate time.Time, userID int, subjectID int, gradeID int) ([]AvailableSlot, error) {

	// Get a connection to the database.
	db, err := config.GetDB2()
	// If there is an error connecting to the database, log the error and return 0 and the error.
	if err != nil {
		log.Println("GetAvailableDemoSlots: failed while trying to connect with database with error: ", err)
		return []AvailableSlot{}, err
	}
	defer db.Close()

	tutorIDs, err := getTutorsFor(subjectID, gradeID, userID)
	if err != nil {
		log.Println("No tutor found this for subject")
		return []AvailableSlot{}, err
	}
	log.Println("tutors", tutorIDs)

	query := `
			SELECT 
				distinct on (start_date)
				(start_date),
				end_date,
				tutor_id 
			FROM 
				tutor_available_slots as tas
			WHERE 
				start_date > $1 
				and date(end_date) < date($2)
				and tutor_id = ANY($3)
				AND NOT EXISTS (
					SELECT 1
					FROM tutor_unavailable_times AS tut
					WHERE 
						tas.tutor_id = tut.tutor_id AND (
							(tas.start_date < tut.end_date AND tas.end_date > tut.start_date)
						)
				)
				AND 
				NOT EXISTS (
						SELECT 1
						FROM session s
						WHERE tas.tutor_id = s.tutor_id AND s.status IN ('active','cancelled') AND(
							(tas.start_date < s.session_end AND tas.end_date > s.session_start)
						)
				)
			ORDER BY start_date;
    	`

	rows, err := db.Query(query, startDate, endDate, pq.Array(tutorIDs))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	slotsMap := make(map[string][]Slot)

	for rows.Next() {
		var tutorID int
		var startDatetime, endDatetime string

		if err := rows.Scan(&startDatetime, &endDatetime, &tutorID); err != nil {
			return nil, err
		}

		date, err := utility.GetDate(startDatetime)
		if err != nil {
			log.Println("GetAvailableDemoSlots: Failed to convert Date with error : ", err)
		}
		slot := Slot{
			TutorID: tutorID,
			Start:   startDatetime,
			End:     endDatetime,
		}
		slotsMap[date] = append(slotsMap[date], slot)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	var availableSlots []AvailableSlot
	for date, slots := range slotsMap {
		availableSlots = append(availableSlots, AvailableSlot{
			Date:  date,
			Day:   utility.DayOfWeek(date),
			Slots: slots,
		})
	}

	sort.Slice(availableSlots, func(i, j int) bool {
		return availableSlots[i].Date < availableSlots[j].Date
	})

	return availableSlots, nil
}

func GetAvailableRescheduleSlots(startDate, endDate time.Time, userID int) ([]Slot, error) {

	// Get a connection to the database.
	db, err := config.GetDB2()
	// If there is an error connecting to the database, log the error and return 0 and the error.
	if err != nil {
		log.Println("GetAvailableDemoSlots: failed while trying to connect with database with error: ", err)
		return []Slot{}, err
	}
	defer db.Close()

	tutorID, err := getPreferedTutor(userID) //getMyBookedSessionTutor(userID)
	log.Println("tutroid", tutorID)

	if err != nil {
		log.Println("No Regular session booked yet")
		return []Slot{}, err
	}

	query := `
			SELECT 
				distinct on (start_date)
				(start_date),
				end_date,
				tutor_id 
			FROM 
				tutor_available_slots as tas
			WHERE 
				start_date > $1 
				and date(end_date) <= date($2)
				and tutor_id = $3
				AND NOT EXISTS (
					SELECT 1
					FROM tutor_unavailable_times AS tut
					WHERE 
						tas.tutor_id = tut.tutor_id AND (
							(tas.start_date < tut.end_date AND tas.end_date > tut.start_date)
						)
				)
				AND 
				NOT EXISTS (
						SELECT 1
						FROM session s
						WHERE tas.tutor_id = s.tutor_id AND s.status IN ('active','cancelled') AND(
							(tas.start_date < s.session_end AND tas.end_date > s.session_start)
						)
				)
			ORDER BY start_date;
    	`

	rows, err := db.Query(query, startDate, endDate, tutorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	//slotsMap := make(map[string][]Slot)
	var availableSlots []Slot

	for rows.Next() {
		var tutorID int
		var startDatetime, endDatetime string

		if err := rows.Scan(&startDatetime, &endDatetime, &tutorID); err != nil {
			return nil, err
		}

		//date, err := utility.GetDate(startDatetime)
		if err != nil {
			log.Println("GetAvailableDemoSlots: Failed to convert Date with error : ", err)
		}
		slot := Slot{
			TutorID: tutorID,
			Start:   startDatetime,
			End:     endDatetime,
		}
		availableSlots = append(availableSlots, slot)
		//slotsMap[date] = append(slotsMap[date], slot)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	// for date, slots := range slotsMap {
	// 	availableSlots = append(availableSlots, AvailableSlot{
	// 		Date:  date,
	// 		Day:   utility.DayOfWeek(date),
	// 		Slots: slots,
	// 	})
	// }
	log.Println("slots", availableSlots)
	sort.Slice(availableSlots, func(i, j int) bool {
		return availableSlots[i].Start < availableSlots[j].Start
	})

	return availableSlots, nil
}

func GetAvailableSlots(startDate, endDate time.Time, userID int, maxSession int, subjectID int, gradeID int, perWeekLimit int) ([]Slot, error) {

	// Get a connection to the database.
	db, err := config.GetDB2()
	// If there is an error connecting to the database, log the error and return 0 and the error.
	if err != nil {
		log.Println("GetAvailableTutor: failed while trying to connect with database with error: ", err)
		return []Slot{}, err
	}
	defer db.Close()

	specificTutor := " " //in case if user have a prefered tutor or demo tutor.

	tutorID, err := getPreferedTutor(userID)
	if err != nil {
		tutorID, err = getDemoTutor(userID)
		if err != nil {
			log.Println("No demo was taken for user")

			if perWeekLimit != 1 {
				tutorID, err = getTutorWithMaxAvailableFreeSlots(startDate, endDate, subjectID, gradeID)
				if err != nil {
					log.Println("GetAvailableTutor: no tutor found ", err)
					return []Slot{}, err
				}
			}

		}
	}

	// tutorID, err := getDemoTutor(userID)
	// if err != nil {
	// 	log.Println("No demo was taken for user")
	// 	tutorID, err = getTutorWithMaxAvailableFreeSlots(startDate, endDate, subjectID, gradeID)
	// 	if err != nil {
	// 		log.Println("GetAvailableTutor: no tutor found ", err)
	// 		return []Slot{}, err
	// 	}
	// }

	formattedStartDate := startDate.Format("2006-01-02 15:04:05")
	formattedEndDate := endDate.Format("2006-01-02 15:04:05")

	if tutorID != 0 {
		specificTutor = fmt.Sprintf(" AND tutor_id = %d ", tutorID)
	}

	// if perWeekLimit == 1 {
	// 	specificTutor = " "
	// }

	// query := fmt.Sprintf(`SELECT
	// 			to_char(start_date, 'HH24:MI:SS') as start_time,
	// 			to_char(end_date, 'HH24:MI:SS') as end_time,
	// 			day_of_week,
	// 			array_agg(tas.start_date ORDER BY tas.start_date) as start_dates,
	// 			array_agg(tas.end_date ORDER BY tas.end_date) as end_dates,
	// 			tas.tutor_id as tutor_id,
	// 			count(*) as count
	// 		FROM
	// 			tutor_available_slots as tas
	// 		WHERE
	// 		    start_date > $1::timestamp
	// 		    AND end_date <= $2::timestamp
	// 			%s
	// 			AND NOT EXISTS (
	// 				SELECT 1
	// 				FROM tutor_unavailable_times AS tut
	// 				WHERE
	// 					tas.tutor_id = tut.tutor_id AND (
	// 						(tas.start_date < tut.end_date AND tas.end_date > tut.start_date)
	// 					)
	// 			)
	// 			AND
	// 			NOT EXISTS (
	// 					SELECT 1
	// 					FROM session s
	// 					WHERE tas.tutor_id = s.tutor_id AND s.status IN ('active','cancelled') AND(
	// 						(tas.start_date < s.session_end AND tas.end_date > s.session_start)
	// 					)
	// 			)
	// 		GROUP BY to_char(start_date, 'HH24:MI:SS'),to_char(end_date, 'HH24:MI:SS'), day_of_week,tutor_id
	// 		HAVING count(*) >= $3
	// 		ORDER BY day_of_week;`, specificTutor)

	query := fmt.Sprintf(`WITH RankedSlots AS (
			SELECT 
				to_char(start_date, 'HH24:MI:SS') as start_time,
				to_char(end_date, 'HH24:MI:SS') as end_time,
				day_of_week,
				array_agg(tas.start_date ORDER BY tas.start_date) as start_dates,
				array_agg(tas.end_date ORDER BY tas.end_date) as end_dates,
				tas.tutor_id as tutor_id,
				count(*) as count,
			    ROW_NUMBER() OVER (PARTITION BY to_char(start_date, 'HH24:MI:SS'), day_of_week) as rn

			FROM
				tutor_available_slots as tas
			WHERE
			    (start_date) > $1::timestamp
			    AND (end_date) <= $2::timestamp
				%s
				AND NOT EXISTS (
					SELECT 1
					FROM tutor_unavailable_times AS tut
					WHERE
						tas.tutor_id = tut.tutor_id AND (
							(tas.start_date < tut.end_date AND tas.end_date > tut.start_date)
						)
				)
				AND
				NOT EXISTS (
						SELECT 1
						FROM session s
						WHERE tas.tutor_id = s.tutor_id AND s.status IN ('active','cancelled') AND(
							(tas.start_date < s.session_end AND tas.end_date > s.session_start)
						)
				)
				GROUP BY 
			to_char(start_date, 'HH24:MI:SS'),
			to_char(end_date, 'HH24:MI:SS'), 
			day_of_week,
			tutor_id
			HAVING count(*) >= $3
			ORDER BY
			day_of_week
			) 
			select * from RankedSlots WHERE rn = 1;`, specificTutor)

	log.Println("query", query)
	log.Print("values", formattedStartDate, formattedEndDate, tutorID, maxSession)
	rows, err := db.Query(query, formattedStartDate, formattedEndDate, maxSession)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	//slotsMap := make(map[string][]Slot)
	var availableSlots []Slot
	for rows.Next() {
		var recurringTimeSlot int
		var dayOfWeek string
		var startTime, endTime string
		var startDates []string
		var endDates []string
		var tutor int
		var rowNumber sql.NullInt64

		if err := rows.Scan(&startTime, &endTime, &dayOfWeek, pq.Array(&startDates), pq.Array(&endDates), &tutor, &recurringTimeSlot, &rowNumber); err != nil {
			return nil, err
		}
		log.Println("data", startTime, endTime, dayOfWeek, recurringTimeSlot)
		if recurringTimeSlot >= maxSession {

			//dates := []SlotDates{}
			for index, date := range startDates {
				// slotDate := SlotDates{
				// 	StartDate: date,
				// 	EndDate:   endDates[index],
				// }
				// dates = append(dates, slotDate)
				slot := Slot{
					Start:   date,
					End:     endDates[index],
					TutorID: tutor,
				}
				availableSlots = append(availableSlots, slot)
			}

			// slot := Slot{
			// 	Start:   startTime,
			// 	End:     endTime,
			// 	TutorID: tutorID,
			// 	Dates:   dates,
			// }

			//slotsMap[dayOfWeek] = append(slotsMap[dayOfWeek], slot)
			//availableSlots = append(availableSlots, slot)

		}

	}

	//log.Println("slots", slotsMap)

	if err = rows.Err(); err != nil {
		return nil, err
	}

	// var availableSlots []AvailableSlot
	// for date, slots := range slotsMap {
	// 	availableSlots = append(availableSlots, AvailableSlot{
	// 		Date:  date,
	// 		Day:   utility.DayOfWeek(date),
	// 		Slots: slots,
	// 	})
	// }

	// sort.Slice(availableSlots, func(i, j int) bool {
	// 	return availableSlots[i].Day < availableSlots[j].Day
	// })
	sort.Slice(availableSlots, func(i, j int) bool {
		return availableSlots[i].Start < availableSlots[j].Start
	})

	return availableSlots, nil
}
func getMyBookedSessionTutor(userID int) (int, error) {

	// Get a connection to the database.
	db, err := config.GetDB2()
	// If there is an error connecting to the database, log the error and return 0 and the error.
	if err != nil {
		log.Println("getDemoTutor: error : ", err)
		return 0, err
	}
	defer db.Close()

	query := `select tutor_id from session where user_id = $1 and type = 'paid' order by session_start desc limit 1`

	tutorID := 0
	err = db.QueryRow(query, userID).Scan(&tutorID)
	if err != nil {
		return tutorID, err
	}
	return tutorID, nil
}
func getDemoTutor(userID int) (int, error) {
	// Get a connection to the database.
	db, err := config.GetDB2()
	// If there is an error connecting to the database, log the error and return 0 and the error.
	if err != nil {
		log.Println("getDemoTutor: error : ", err)
		return 0, err
	}
	defer db.Close()

	query := `select tutor_id from session where user_id = $1 and type = 'demo'`

	tutorID := 0
	err = db.QueryRow(query, userID).Scan(&tutorID)
	if err != nil {
		return tutorID, err
	}
	return tutorID, nil

}
func getPreferedTutor(userID int) (int, error) {
	// Get a connection to the database.
	db, err := config.GetDB2()
	// If there is an error connecting to the database, log the error and return 0 and the error.
	if err != nil {
		log.Println("getDemoTutor: error : ", err)
		return 0, err
	}
	defer db.Close()

	query := `select distinct tutor_id 
	from student_session_preference as ssp,
	user2subscription as u2s 
	where 
	ssp.user_id=u2s.user_id 
	and u2s.status='active' 
	and ssp.user_id=$1`

	tutorID := 0
	err = db.QueryRow(query, userID).Scan(&tutorID)
	if err != nil {
		return tutorID, err
	}
	return tutorID, nil

}
func getTutorsFor(subjectID int, gradeID int, userID int) ([]int, error) {
	// Get a connection to the database.
	db, err := config.GetDB2()
	// If there is an error connecting to the database, log the error and return 0 and the error.
	if err != nil {
		log.Println("getTutorFor: error : ", err)
		return []int{}, err
	}
	defer db.Close()

	query := `select 
			   tutor_id 
			   from 
			   tutor_subject_grade 
			   where 
			   subject_id = $1
			   and grade_id=$2
			   and tutor_id not in (select tutor_id from session where user_id = $3 and type='demo' and status = 'completed')
			   `

	tutorIDs := []int{}
	rows, err := db.Query(query, subjectID, gradeID, userID)
	if err != nil {
		return tutorIDs, err
	}
	// Iterate over the result set
	for rows.Next() {
		// Variables to hold the database values for each column.
		tutorID := 0

		// Scan the database values into the variables.
		err = rows.Scan(&tutorID)
		if err != nil {
			log.Println("[ERROR] GetTutorCalendar: Failed to scan the result with error:", err)
			continue // Continue with the next row if there's an error in scanning.
		}
		tutorIDs = append(tutorIDs, tutorID)
	}

	return tutorIDs, nil
}
func getTutorWithMaxAvailableFreeSlots(startDate, endDate time.Time, subjectID int, gradeID int) (int, error) {

	// Get a connection to the database.
	db, err := config.GetDB2()
	// If there is an error connecting to the database, log the error and return 0 and the error.
	if err != nil {
		log.Println("getDemoTutor: error : ", err)
		return 0, err
	}
	defer db.Close()

	query := `
			SELECT 
				tas.tutor_id, 
			    count(*)
			FROM 
				tutor_available_slots as tas
			INNER JOIN tutor_subject_grade as tsg on tas.tutor_id=tsg.tutor_id and tsg.subject_id=$3 and tsg.grade_id=$4
			WHERE 
			start_date > $1
			AND date(end_date) < date($2)
			AND NOT EXISTS (
			    SELECT 1
			    FROM tutor_unavailable_times AS tut
			    WHERE 
			        tas.tutor_id = tut.tutor_id AND (
			            (tas.start_date < tut.end_date AND tas.end_date > tut.start_date)
			        )
			)
			AND 
			NOT EXISTS (
			        SELECT 1
			        FROM session s
			        WHERE tas.tutor_id = s.tutor_id AND s.status IN ('active','cancelled') AND(
			            (tas.start_date < s.session_end AND tas.end_date > s.session_start)
			        )
			)
			GROUP BY tas.tutor_id
			ORDER BY count(*) desc
			LIMIT 1;`

	tutorID := 0
	maxSlots := 0
	err = db.QueryRow(query, startDate, endDate, subjectID, gradeID).Scan(&tutorID, &maxSlots)
	if err != nil {
		return tutorID, err
	}
	return tutorID, nil
}

// GetTutorByID METHOD, fetches a tutor's details from the database using their ID and updates the provided Tutor
// struct with the retrieved data. By using a pointer to the Tutor struct, the method directly modifies the original struct,
// ensuring that the updated information is available to the calling code. This approach is efficient and helps in
// managing memory usage effectively.
func GetTutorByID(id int) (Tutor, error) {
	var (
		tutorId               int64
		email                 string
		phoneNumber           sql.NullString
		name                  string
		pictureUrl            sql.NullString
		createdAt             time.Time
		autogeneratedPassword sql.NullBool
		queryParams           sql.NullString
		password              string
		timezone              sql.NullString
		meetingLink           sql.NullString
	)
	db, err := config.GetDB2()
	if err != nil {
		log.Println("[ERROR] GetTutorIdBytoken: Failed to connect with database with error: ", err)
		return Tutor{}, err
	}
	defer db.Close()
	query := ` SELECT 
				id,
				email_id,
				phone_number,
				name,
				picture_url,
				created_at,
				autogenerated_pass,
				query_params,
				password,
				timezone,
				meeting_link
			FROM 
				tutor
			WHERE 
				id = $1`
	err = db.QueryRow(query, id).Scan(
		&tutorId,
		&email,
		&phoneNumber,
		&name,
		&pictureUrl,
		&createdAt,
		&autogeneratedPassword,
		&queryParams,
		&password,
		&timezone,
		&meetingLink,
	)
	if err != nil {
		log.Println("[ERROR] GetTutorIdBytoken: Failed to execute the query with error: ", err)
		return Tutor{}, err
	}
	tutor := Tutor{
		ID:                    id,
		TutorEmail:            email,
		Phone:                 utility.SQLNullStringToString(phoneNumber),
		TutorName:             name,
		PictureURL:            utility.SQLNullStringToString(pictureUrl),
		CreatedAt:             createdAt.Format("2006-01-02"),
		AutogeneratedPassword: utility.SQLNullBoolToBool(autogeneratedPassword),
		QueryParams:           utility.SQLNullStringToString(queryParams),
		HashPassword:          password,
		Timezone:              timezone.String,
		ZoomLink:              utility.SQLNullStringToString(meetingLink),
	}
	return tutor, nil
}
