ALTER TABLE tutor
ADD COLUMN autogenerated_pass boolean,
ADD COLUMN query_params VARCHAR;

COMMENT ON COLUMN tutor.autogenerated_pass IS ' whether the password is system generated or not.';
COMMENT ON COLUMN tutor.query_params IS ' query parameter from where user is registered';

ALTER TABLE "tutor_auth" DROP CONSTRAINT "tutor_auth_id_fkey";